pipeline {
    agent any
    
    stages {
        stage('Pre-requisites') {
            steps {
                script {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t devops-assignment .'
                }
            }
        }
        
                
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 8000:8000 devops-assignment'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'pytest'
                }
            }
        }
    }
}
