pipeline {
    agent any
    
    stages {
        stage('Pre-requisites') {
            steps {
                script {
                    sh 'python3 -m venv venv'
                    sh '. venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t devops-assignment .'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    sh 'pytest'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -p 8000:8000 devops-assignment'
                }
            }
        }
        
        stage('Cleanup') {
            steps {
                script {
                    sh 'rm -rf venv'
                }
            }
        }
    }
    
    post {
        always {
            sh 'docker rm -f $(docker ps -aq)'
        }
    }
}
