pipeline {
    agent any
    
    stages {
        stage('Pre-requisites') {
            steps {
                script {
                    sh 'python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t devops-assignment .'
                }
            }
        }
        
                
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 8000:8000 devops-assignment'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh '. venv/bin/activate && pytest'
                }
            }
        }
        stage('Cleanup') {
            steps {
                script {
                    sh 'rm -rf venv'
                }
            }
        }

    }
}
